### ISSUE TITLE
Tutorial 2 screen: Change text to

### ISSUE THREAD

**Issue by marybethdawson** [engagementgamelab/opportunity-game#178]
"Strengthen these 3 abilities to unlock more opportunities and increase your score"
then 3 icons, then
"Get a" [Bus Pass and Job icons, with the word 'and' in between] "to increase your score"

**Comment by johnnycrich** [comment]
@marybethdawson These changes make the screen too large and cut off the button at the bottom.

**Comment by marybethdawson** [comment]
@johnnycrich @courtneylord What if we put 1 line above the bus/job icons saying "Get these to increase your score" and make those icons smaller? Does that help?

**Comment by johnnycrich** [comment]
@marybethdawson In the next build I made the font on the screen smaller -- let's see how it looks to everyone.
