### ISSUE TITLE
Stop city scrolling animation if player starts scrolling

### ISSUE THREAD

**Issue by johnnycrich** [engagementgamelab/opportunity-game#184]

**Comment by johnnycrich** [comment]
In lieu of this I disable ability to click categories during intro scroll.

**Comment by marybethdawson** [comment]
This still happens to me on desktop. The city scroll keeps going down to the bottom even when I start scrolling.

**Comment by johnnycrich** [comment]
@marybethdawson Stopping auto-scroll when player starts scrolling will not be possible for our shippable. I am closing this issue for now.

**Comment by marybethdawson** [comment]
Ok, no problem
