### ISSUE TITLE
Delay end-of-round screen until you've decided Yes or No on an opportunity event

### ISSUE THREAD

**Issue by marybethdawson** [engagementgamelab/opportunity-game#61]
(If the opportunity event and end-of-round coincide)
Verify with just this morning (5/16)

**Comment by johnnycrich** [comment]
@marybethdawson Can you give example of which exact screen this is?

**Comment by marybethdawson** [comment]
@johnnycrich I'm going to close this; it's irrelevant now. This was from before when the opportunity events weren't working yet and the end-of-round events didn't show before the round ended.
